#!/bin/sh

mkdir $THEOS/frameworks
cp -r .theos/obj/SettingsKit.framework $THEOS/frameworks

mkdir $THEOS/include/SettingsKit/
mkdir $THEOS/include/SettingsKit/Resources
mkdir $THEOS/include/SettingsKit/Preferences
cp Preferences/* $THEOS/include/SettingsKit/Preferences
cp *.h $THEOS/include/SettingsKit/
cp *.m $THEOS/include/SettingsKit/
cp Resources/* $THEOS/include/SettingsKit/Resources/
